### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raulriera**

### CODE REVIEW

**Comment by raulriera** [comment]
Can I get a single approval please, not 2

**Comment by raulriera** [comment]
Nope, bot doesn't work and I don;'t know javascript then

**Comment by dannbeaus** [comment]
whats the threshold

**Comment by raulriera** [comment]
Dismiss review and review again please? 😭

**Comment by raulriera** [comment]
Testing something reveal quick

- [ ] yes
- [ ] no

**Comment by raulriera** [comment]
Another comment

**Comment by raulriera** [comment]
Commmeasasd

**Pull request closed without merging**
